module Turbopuffer
  module Models
    type attribute_schema_config =
      {
        type: String,
        ann: Turbopuffer::Models::AttributeSchemaConfig::ann,
        filterable: bool,
        full_text_search: Turbopuffer::Models::full_text_search,
        regex: bool
      }

    class AttributeSchemaConfig < Turbopuffer::Internal::Type::BaseModel
      attr_accessor type: String

      attr_reader ann: Turbopuffer::Models::AttributeSchemaConfig::ann?

      def ann=: (
        Turbopuffer::Models::AttributeSchemaConfig::ann
      ) -> Turbopuffer::Models::AttributeSchemaConfig::ann

      attr_reader filterable: bool?

      def filterable=: (bool) -> bool

      attr_reader full_text_search: Turbopuffer::Models::full_text_search?

      def full_text_search=: (
        Turbopuffer::Models::full_text_search
      ) -> Turbopuffer::Models::full_text_search

      attr_reader regex: bool?

      def regex=: (bool) -> bool

      def initialize: (
        type: String,
        ?ann: Turbopuffer::Models::AttributeSchemaConfig::ann,
        ?filterable: bool,
        ?full_text_search: Turbopuffer::Models::full_text_search,
        ?regex: bool
      ) -> void

      def to_hash: -> {
        type: String,
        ann: Turbopuffer::Models::AttributeSchemaConfig::ann,
        filterable: bool,
        full_text_search: Turbopuffer::Models::full_text_search,
        regex: bool
      }

      type ann = bool | Turbopuffer::AttributeSchemaConfig::Ann::AnnConfig

      module Ann
        extend Turbopuffer::Internal::Type::Union

        type ann_config =
          { distance_metric: Turbopuffer::Models::distance_metric }

        class AnnConfig < Turbopuffer::Internal::Type::BaseModel
          attr_reader distance_metric: Turbopuffer::Models::distance_metric?

          def distance_metric=: (
            Turbopuffer::Models::distance_metric
          ) -> Turbopuffer::Models::distance_metric

          def initialize: (
            ?distance_metric: Turbopuffer::Models::distance_metric
          ) -> void

          def to_hash: -> {
            distance_metric: Turbopuffer::Models::distance_metric
          }
        end

        def self?.variants: -> ::Array[Turbopuffer::Models::AttributeSchemaConfig::ann]
      end
    end
  end
end
