module Turbopuffer
  module Models
    type bm25_clause_params = { last_as_prefix: bool }

    class Bm25ClauseParams < Turbopuffer::Internal::Type::BaseModel
      attr_reader last_as_prefix: bool?

      def last_as_prefix=: (bool) -> bool

      def initialize: (?last_as_prefix: bool) -> void

      def to_hash: -> { last_as_prefix: bool }
    end
  end
end
