module Turbopuffer
  module Models
    type highlight_fragment_by = :none | :sentence | :paragraph | :word

    module HighlightFragmentBy
      extend Turbopuffer::Internal::Type::Enum

      # Treat the whole attribute as a single fragment.
      NONE: :none

      # Split the attribute into sentences. This is the default.
      SENTENCE: :sentence

      # Split the attribute into paragraphs.
      PARAGRAPH: :paragraph

      # Split the attribute into individual words.
      WORD: :word

      def self?.values: -> ::Array[Turbopuffer::Models::highlight_fragment_by]
    end
  end
end
