module Turbopuffer
  module Models
    type limit = { total: Integer, per: Turbopuffer::Limit::Per }

    class Limit < Turbopuffer::Internal::Type::BaseModel
      attr_accessor total: Integer

      attr_reader per: Turbopuffer::Limit::Per?

      def per=: (Turbopuffer::Limit::Per) -> Turbopuffer::Limit::Per

      def initialize: (total: Integer, ?per: Turbopuffer::Limit::Per) -> void

      def to_hash: -> { total: Integer, per: Turbopuffer::Limit::Per }

      type per = { attributes: ::Array[String], limit: Integer }

      class Per < Turbopuffer::Internal::Type::BaseModel
        attr_accessor attributes: ::Array[String]

        attr_accessor limit: Integer

        def initialize: (attributes: ::Array[String], limit: Integer) -> void

        def to_hash: -> { attributes: ::Array[String], limit: Integer }
      end
    end
  end
end
