module Turbopuffer
  module Models
    type namespace_metadata =
      {
        approx_logical_bytes: Integer,
        approx_row_count: Integer,
        created_at: Time,
        schema: ::Hash[Symbol, Turbopuffer::AttributeSchemaConfig],
        updated_at: Time,
        encryption: Turbopuffer::Models::NamespaceMetadata::encryption,
        index: Turbopuffer::Models::NamespaceMetadata::index
      }

    class NamespaceMetadata < Turbopuffer::Internal::Type::BaseModel
      attr_accessor approx_logical_bytes: Integer

      attr_accessor approx_row_count: Integer

      attr_accessor created_at: Time

      attr_accessor schema: ::Hash[Symbol, Turbopuffer::AttributeSchemaConfig]

      attr_accessor updated_at: Time

      attr_reader encryption: Turbopuffer::Models::NamespaceMetadata::encryption?

      def encryption=: (
        Turbopuffer::Models::NamespaceMetadata::encryption
      ) -> Turbopuffer::Models::NamespaceMetadata::encryption

      attr_reader index: Turbopuffer::Models::NamespaceMetadata::index?

      def index=: (
        Turbopuffer::Models::NamespaceMetadata::index
      ) -> Turbopuffer::Models::NamespaceMetadata::index

      def initialize: (
        approx_logical_bytes: Integer,
        approx_row_count: Integer,
        created_at: Time,
        schema: ::Hash[Symbol, Turbopuffer::AttributeSchemaConfig],
        updated_at: Time,
        ?encryption: Turbopuffer::Models::NamespaceMetadata::encryption,
        ?index: Turbopuffer::Models::NamespaceMetadata::index
      ) -> void

      def to_hash: -> {
        approx_logical_bytes: Integer,
        approx_row_count: Integer,
        created_at: Time,
        schema: ::Hash[Symbol, Turbopuffer::AttributeSchemaConfig],
        updated_at: Time,
        encryption: Turbopuffer::Models::NamespaceMetadata::encryption,
        index: Turbopuffer::Models::NamespaceMetadata::index
      }

      type encryption = bool | Turbopuffer::NamespaceMetadata::Encryption::Cmek

      module Encryption
        extend Turbopuffer::Internal::Type::Union

        type cmek =
          { cmek: Turbopuffer::NamespaceMetadata::Encryption::Cmek::Cmek }

        class Cmek < Turbopuffer::Internal::Type::BaseModel
          attr_reader cmek: Turbopuffer::NamespaceMetadata::Encryption::Cmek::Cmek?

          def cmek=: (
            Turbopuffer::NamespaceMetadata::Encryption::Cmek::Cmek
          ) -> Turbopuffer::NamespaceMetadata::Encryption::Cmek::Cmek

          def initialize: (
            ?cmek: Turbopuffer::NamespaceMetadata::Encryption::Cmek::Cmek
          ) -> void

          def to_hash: -> {
            cmek: Turbopuffer::NamespaceMetadata::Encryption::Cmek::Cmek
          }

          type cmek = { key_name: String }

          class Cmek < Turbopuffer::Internal::Type::BaseModel
            attr_accessor key_name: String

            def initialize: (key_name: String) -> void

            def to_hash: -> { key_name: String }
          end
        end

        def self?.variants: -> ::Array[Turbopuffer::Models::NamespaceMetadata::encryption]
      end

      type index =
        Turbopuffer::NamespaceMetadata::Index::Status
        | Turbopuffer::NamespaceMetadata::Index::UnionMember1

      module Index
        extend Turbopuffer::Internal::Type::Union

        type status = { status: :"up-to-date" }

        class Status < Turbopuffer::Internal::Type::BaseModel
          attr_accessor status: :"up-to-date"

          def initialize: (?status: :"up-to-date") -> void

          def to_hash: -> { status: :"up-to-date" }
        end

        type union_member1 = { status: :updating, unindexed_bytes: Integer }

        class UnionMember1 < Turbopuffer::Internal::Type::BaseModel
          attr_accessor status: :updating

          attr_accessor unindexed_bytes: Integer

          def initialize: (unindexed_bytes: Integer, ?status: :updating) -> void

          def to_hash: -> { status: :updating, unindexed_bytes: Integer }
        end

        def self?.variants: -> ::Array[Turbopuffer::Models::NamespaceMetadata::index]
      end
    end
  end
end
