module Turbopuffer
  module Models
    type namespace_start_copy_from_response = { token: String }

    class NamespaceStartCopyFromResponse < Turbopuffer::Internal::Type::BaseModel
      attr_accessor token: String

      def initialize: (token: String) -> void

      def to_hash: -> { token: String }
    end
  end
end
