module Turbopuffer
  module Models
    type namespace_metadata =
      {
        approx_logical_bytes: Integer,
        approx_row_count: Integer,
        created_at: Time,
        schema: ::Hash[Symbol, Turbopuffer::AttributeSchemaConfig]
      }

    class NamespaceMetadata < Turbopuffer::Internal::Type::BaseModel
      attr_accessor approx_logical_bytes: Integer

      attr_accessor approx_row_count: Integer

      attr_accessor created_at: Time

      attr_accessor schema: ::Hash[Symbol, Turbopuffer::AttributeSchemaConfig]

      def initialize: (
        approx_logical_bytes: Integer,
        approx_row_count: Integer,
        created_at: Time,
        schema: ::Hash[Symbol, Turbopuffer::AttributeSchemaConfig]
      ) -> void

      def to_hash: -> {
        approx_logical_bytes: Integer,
        approx_row_count: Integer,
        created_at: Time,
        schema: ::Hash[Symbol, Turbopuffer::AttributeSchemaConfig]
      }
    end
  end
end
