module Turbopuffer
  module Models
    type namespace_write_response =
      {
        billing: Turbopuffer::WriteBilling,
        message: String,
        rows_affected: Integer,
        status: :OK,
        rows_deleted: Integer,
        rows_patched: Integer,
        rows_upserted: Integer
      }

    class NamespaceWriteResponse < Turbopuffer::Internal::Type::BaseModel
      attr_accessor billing: Turbopuffer::WriteBilling

      attr_accessor message: String

      attr_accessor rows_affected: Integer

      attr_accessor status: :OK

      attr_reader rows_deleted: Integer?

      def rows_deleted=: (Integer) -> Integer

      attr_reader rows_patched: Integer?

      def rows_patched=: (Integer) -> Integer

      attr_reader rows_upserted: Integer?

      def rows_upserted=: (Integer) -> Integer

      def initialize: (
        billing: Turbopuffer::WriteBilling,
        message: String,
        rows_affected: Integer,
        ?rows_deleted: Integer,
        ?rows_patched: Integer,
        ?rows_upserted: Integer,
        ?status: :OK
      ) -> void

      def to_hash: -> {
        billing: Turbopuffer::WriteBilling,
        message: String,
        rows_affected: Integer,
        status: :OK,
        rows_deleted: Integer,
        rows_patched: Integer,
        rows_upserted: Integer
      }
    end
  end
end
