module Turbopuffer
  module Models
    type namespace_branch_from_params =
      { namespace: String, source_namespace: String }
      & Turbopuffer::Internal::Type::request_parameters

    class NamespaceBranchFromParams < Turbopuffer::Internal::Type::BaseModel
      extend Turbopuffer::Internal::Type::RequestParameters::Converter
      include Turbopuffer::Internal::Type::RequestParameters

      attr_reader namespace: String?

      def namespace=: (String) -> String

      attr_accessor source_namespace: String

      def initialize: (
        source_namespace: String,
        ?namespace: String,
        ?request_options: Turbopuffer::request_opts
      ) -> void

      def to_hash: -> {
        namespace: String,
        source_namespace: String,
        request_options: Turbopuffer::RequestOptions
      }
    end
  end
end
