module Turbopuffer
  module Models
    type namespace_branch_from_params =
      {
        namespace: String,
        branch_from_namespace: Turbopuffer::Models::branch_from_namespace_params
      }
      & Turbopuffer::Internal::Type::request_parameters

    class NamespaceBranchFromParams < Turbopuffer::Internal::Type::BaseModel
      extend Turbopuffer::Internal::Type::RequestParameters::Converter
      include Turbopuffer::Internal::Type::RequestParameters

      attr_reader namespace: String?

      def namespace=: (String) -> String

      attr_accessor branch_from_namespace: Turbopuffer::Models::branch_from_namespace_params

      def initialize: (
        branch_from_namespace: Turbopuffer::Models::branch_from_namespace_params,
        ?namespace: String,
        ?request_options: Turbopuffer::request_opts
      ) -> void

      def to_hash: -> {
        namespace: String,
        branch_from_namespace: Turbopuffer::Models::branch_from_namespace_params,
        request_options: Turbopuffer::RequestOptions
      }
    end
  end
end
