module Turbopuffer
  module Models
    type namespace_metadata_patch =
      {
        pinning: Turbopuffer::Models::NamespaceMetadataPatch::pinning?,
        read_only: bool
      }

    class NamespaceMetadataPatch < Turbopuffer::Internal::Type::BaseModel
      attr_accessor pinning: Turbopuffer::Models::NamespaceMetadataPatch::pinning?

      attr_reader read_only: bool?

      def read_only=: (bool) -> bool

      def initialize: (
        ?pinning: Turbopuffer::Models::NamespaceMetadataPatch::pinning?,
        ?read_only: bool
      ) -> void

      def to_hash: -> {
        pinning: Turbopuffer::Models::NamespaceMetadataPatch::pinning?,
        read_only: bool
      }

      type pinning = bool | Turbopuffer::PinningConfig

      module Pinning
        extend Turbopuffer::Internal::Type::Union

        def self?.variants: -> ::Array[Turbopuffer::Models::NamespaceMetadataPatch::pinning]
      end
    end
  end
end
