module Turbopuffer
  module Models
    type namespace_delete_all_response = { status: :OK }

    class NamespaceDeleteAllResponse < Turbopuffer::Internal::Type::BaseModel
      attr_accessor status: :OK

      def initialize: (?status: :OK) -> void

      def to_hash: -> { status: :OK }
    end
  end
end
