module Turbopuffer
  module Models
    type namespace_hint_cache_warm_response = { status: :OK, message: String }

    class NamespaceHintCacheWarmResponse < Turbopuffer::Internal::Type::BaseModel
      attr_accessor status: :OK

      attr_reader message: String?

      def message=: (String) -> String

      def initialize: (?message: String, ?status: :OK) -> void

      def to_hash: -> { status: :OK, message: String }
    end
  end
end
