module Turbopuffer
  module Models
    type namespace_metadata =
      {
        approx_logical_bytes: Integer,
        approx_row_count: Integer,
        created_at: Time,
        encryption: Turbopuffer::Models::encryption,
        index: Turbopuffer::Models::NamespaceMetadata::index,
        schema: ::Hash[Symbol, Turbopuffer::AttributeSchemaConfig],
        updated_at: Time,
        pinning: Turbopuffer::NamespaceMetadata::Pinning
      }

    class NamespaceMetadata < Turbopuffer::Internal::Type::BaseModel
      attr_accessor approx_logical_bytes: Integer

      attr_accessor approx_row_count: Integer

      attr_accessor created_at: Time

      attr_accessor encryption: Turbopuffer::Models::encryption

      attr_accessor index: Turbopuffer::Models::NamespaceMetadata::index

      attr_accessor schema: ::Hash[Symbol, Turbopuffer::AttributeSchemaConfig]

      attr_accessor updated_at: Time

      attr_reader pinning: Turbopuffer::NamespaceMetadata::Pinning?

      def pinning=: (
        Turbopuffer::NamespaceMetadata::Pinning
      ) -> Turbopuffer::NamespaceMetadata::Pinning

      def initialize: (
        approx_logical_bytes: Integer,
        approx_row_count: Integer,
        created_at: Time,
        encryption: Turbopuffer::Models::encryption,
        index: Turbopuffer::Models::NamespaceMetadata::index,
        schema: ::Hash[Symbol, Turbopuffer::AttributeSchemaConfig],
        updated_at: Time,
        ?pinning: Turbopuffer::NamespaceMetadata::Pinning
      ) -> void

      def to_hash: -> {
        approx_logical_bytes: Integer,
        approx_row_count: Integer,
        created_at: Time,
        encryption: Turbopuffer::Models::encryption,
        index: Turbopuffer::Models::NamespaceMetadata::index,
        schema: ::Hash[Symbol, Turbopuffer::AttributeSchemaConfig],
        updated_at: Time,
        pinning: Turbopuffer::NamespaceMetadata::Pinning
      }

      type index =
        Turbopuffer::NamespaceMetadata::Index::IndexUpToDate
        | Turbopuffer::NamespaceMetadata::Index::IndexUpdating

      module Index
        extend Turbopuffer::Internal::Type::Union

        type index_up_to_date = { status: :"up-to-date" }

        class IndexUpToDate < Turbopuffer::Internal::Type::BaseModel
          attr_accessor status: :"up-to-date"

          def initialize: (?status: :"up-to-date") -> void

          def to_hash: -> { status: :"up-to-date" }
        end

        type index_updating = { status: :updating, unindexed_bytes: Integer }

        class IndexUpdating < Turbopuffer::Internal::Type::BaseModel
          attr_accessor status: :updating

          attr_accessor unindexed_bytes: Integer

          def initialize: (unindexed_bytes: Integer, ?status: :updating) -> void

          def to_hash: -> { status: :updating, unindexed_bytes: Integer }
        end

        def self?.variants: -> ::Array[Turbopuffer::Models::NamespaceMetadata::index]
      end

      type pinning = { status: Turbopuffer::NamespaceMetadata::Pinning::Status }

      class Pinning < Turbopuffer::Models::PinningConfig
        def status: -> Turbopuffer::NamespaceMetadata::Pinning::Status?

        def status=: (
          Turbopuffer::NamespaceMetadata::Pinning::Status _
        ) -> Turbopuffer::NamespaceMetadata::Pinning::Status

        def initialize: (
          ?status: Turbopuffer::NamespaceMetadata::Pinning::Status
        ) -> void

        def to_hash: -> {
          status: Turbopuffer::NamespaceMetadata::Pinning::Status
        }

        type status =
          { ready_replicas: Integer, updated_at: Time, utilization: Float }

        class Status < Turbopuffer::Internal::Type::BaseModel
          attr_accessor ready_replicas: Integer

          attr_accessor updated_at: Time

          attr_accessor utilization: Float

          def initialize: (
            ready_replicas: Integer,
            updated_at: Time,
            utilization: Float
          ) -> void

          def to_hash: -> {
            ready_replicas: Integer,
            updated_at: Time,
            utilization: Float
          }
        end
      end
    end
  end
end
