module Turbopuffer
  module Models
    type namespace_copy_from_params =
      {
        namespace: String,
        source_namespace: String,
        source_api_key: String,
        source_region: String
      }
      & Turbopuffer::Internal::Type::request_parameters

    class NamespaceCopyFromParams < Turbopuffer::Internal::Type::BaseModel
      extend Turbopuffer::Internal::Type::RequestParameters::Converter
      include Turbopuffer::Internal::Type::RequestParameters

      attr_reader namespace: String?

      def namespace=: (String) -> String

      attr_accessor source_namespace: String

      attr_reader source_api_key: String?

      def source_api_key=: (String) -> String

      attr_reader source_region: String?

      def source_region=: (String) -> String

      def initialize: (
        source_namespace: String,
        ?namespace: String,
        ?source_api_key: String,
        ?source_region: String,
        ?request_options: Turbopuffer::request_opts
      ) -> void

      def to_hash: -> {
        namespace: String,
        source_namespace: String,
        source_api_key: String,
        source_region: String,
        request_options: Turbopuffer::RequestOptions
      }
    end
  end
end
