module Turbopuffer
  module Models
    type query =
      {
        aggregate_by: ::Hash[Symbol, top],
        distance_metric: Turbopuffer::Models::distance_metric,
        exclude_attributes: ::Array[String],
        filters: top,
        group_by: ::Array[String],
        include_attributes: Turbopuffer::Models::include_attributes,
        limit: Turbopuffer::Models::Query::limit,
        rank_by: top,
        top_k: Integer
      }

    class Query < Turbopuffer::Internal::Type::BaseModel
      attr_reader aggregate_by: ::Hash[Symbol, top]?

      def aggregate_by=: (::Hash[Symbol, top]) -> ::Hash[Symbol, top]

      attr_reader distance_metric: Turbopuffer::Models::distance_metric?

      def distance_metric=: (
        Turbopuffer::Models::distance_metric
      ) -> Turbopuffer::Models::distance_metric

      attr_reader exclude_attributes: ::Array[String]?

      def exclude_attributes=: (::Array[String]) -> ::Array[String]

      attr_reader filters: top?

      def filters=: (top) -> top

      attr_reader group_by: ::Array[String]?

      def group_by=: (::Array[String]) -> ::Array[String]

      attr_reader include_attributes: Turbopuffer::Models::include_attributes?

      def include_attributes=: (
        Turbopuffer::Models::include_attributes
      ) -> Turbopuffer::Models::include_attributes

      attr_reader limit: Turbopuffer::Models::Query::limit?

      def limit=: (
        Turbopuffer::Models::Query::limit
      ) -> Turbopuffer::Models::Query::limit

      attr_reader rank_by: top?

      def rank_by=: (top) -> top

      attr_reader top_k: Integer?

      def top_k=: (Integer) -> Integer

      def initialize: (
        ?aggregate_by: ::Hash[Symbol, top],
        ?distance_metric: Turbopuffer::Models::distance_metric,
        ?exclude_attributes: ::Array[String],
        ?filters: top,
        ?group_by: ::Array[String],
        ?include_attributes: Turbopuffer::Models::include_attributes,
        ?limit: Turbopuffer::Models::Query::limit,
        ?rank_by: top,
        ?top_k: Integer
      ) -> void

      def to_hash: -> {
        aggregate_by: ::Hash[Symbol, top],
        distance_metric: Turbopuffer::Models::distance_metric,
        exclude_attributes: ::Array[String],
        filters: top,
        group_by: ::Array[String],
        include_attributes: Turbopuffer::Models::include_attributes,
        limit: Turbopuffer::Models::Query::limit,
        rank_by: top,
        top_k: Integer
      }

      type limit = Integer | Turbopuffer::Query::Limit::Limit

      module Limit
        extend Turbopuffer::Internal::Type::Union

        type limit =
          { total: Integer, per: Turbopuffer::Query::Limit::Limit::Per }

        class Limit < Turbopuffer::Internal::Type::BaseModel
          attr_accessor total: Integer

          attr_reader per: Turbopuffer::Query::Limit::Limit::Per?

          def per=: (
            Turbopuffer::Query::Limit::Limit::Per
          ) -> Turbopuffer::Query::Limit::Limit::Per

          def initialize: (
            total: Integer,
            ?per: Turbopuffer::Query::Limit::Limit::Per
          ) -> void

          def to_hash: -> {
            total: Integer,
            per: Turbopuffer::Query::Limit::Limit::Per
          }

          type per = { attributes: ::Array[String], limit: Integer }

          class Per < Turbopuffer::Internal::Type::BaseModel
            attr_accessor attributes: ::Array[String]

            attr_accessor limit: Integer

            def initialize: (
              attributes: ::Array[String],
              limit: Integer
            ) -> void

            def to_hash: -> { attributes: ::Array[String], limit: Integer }
          end
        end

        def self?.variants: -> ::Array[Turbopuffer::Models::Query::limit]
      end
    end
  end
end
