module Turbopuffer
  module Models
    type tokenizer =
      :pre_tokenized_array | :word_v0 | :word_v1 | :word_v2 | :word_v3

    module Tokenizer
      extend Turbopuffer::Internal::Type::Enum

      PRE_TOKENIZED_ARRAY: :pre_tokenized_array
      WORD_V0: :word_v0
      WORD_V1: :word_v1
      WORD_V2: :word_v2
      WORD_V3: :word_v3

      def self?.values: -> ::Array[Turbopuffer::Models::tokenizer]
    end
  end
end
